app/src/Entity/Adherent.php
<?php

namespace App\Entity;

use App\Repository\AdherentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AdherentRepository::class)
 */
class Adherent
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Votre prénom ne peut pas être vide")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotNull(message="Votre nom ne peut pas être vide")
     */
    private $lastname;

    /**
     * @ORM\Column(type="boolean")
     * @Assert\NotNull(message="Veuillez choisir votre genre")
     */
    private $gender;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotNull(message="Votre date de naissance est requise.")
     */
    private $birthday;

    /**
     * @ORM\OneToOne(targetEntity=User::class, mappedBy="adherent", cascade={"persist", "remove"})
     */
    private $user_account;

    /**
     * @ORM\ManyToMany(targetEntity=Association::class, inversedBy="adherents")
     */
    private $associations;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $bio;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $search;

    /**
     * @ORM\OneToMany(targetEntity=Cagnotte::class, mappedBy="donateur")
     */
    private $cagnottes;

    /**
     * @ORM\OneToMany(targetEntity=Conversation::class, mappedBy="adherent", orphanRemoval=true)
     */
    private $conversations;

    /**
     * @ORM\OneToMany(targetEntity=EventAdherent::class, mappedBy="adherent", orphanRemoval=true)
     */
    private $eventAdherents;

    public function __construct()
    {
        $this->associations = new ArrayCollection();
        $this->cagnottes = new ArrayCollection();
        $this->conversations = new ArrayCollection();
        $this->eventAdherents = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getGender(): ?bool
    {
        return $this->gender;
    }

    public function setGender(bool $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getUserAccount(): ?User
    {
        return $this->user_account;
    }

    public function setUserAccount(?User $user_account): self
    {
        // unset the owning side of the relation if necessary
        if ($user_account === null && $this->user_account !== null) {
            $this->user_account->setAdherent(null);
        }

        // set the owning side of the relation if necessary
        if ($user_account !== null && $user_account->getAdherent() !== $this) {
            $user_account->setAdherent($this);
        }

        $this->user_account = $user_account;

        return $this;
    }

    /**
     * @return Collection|Association[]
     */
    public function getAssociations(): Collection
    {
        return $this->associations;
    }

    public function addAssociation(Association $association): self
    {
        if (!$this->associations->contains($association)) {
            $this->associations[] = $association;
        }

        return $this;
    }

    public function removeAssociation(Association $association): self
    {
        $this->associations->removeElement($association);

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

    public function getSearch(): ?string
    {
        return $this->search;
    }

    public function setSearch(string $search): self
    {
        $this->search = $search;

        return $this;
    }


    /**
     * @return Collection|Cagnotte[]
     */
    public function getCagnottes(): Collection
    {
        return $this->cagnottes;
    }

    public function addCagnotte(Cagnotte $cagnotte): self
    {
        if (!$this->cagnottes->contains($cagnotte)) {
            $this->cagnottes[] = $cagnotte;
            $cagnotte->setDonateur($this);
        }

        return $this;
    }

    public function removeCagnotte(Cagnotte $cagnotte): self
    {
        if ($this->cagnottes->removeElement($cagnotte)) {
            // set the owning side to null (unless already changed)
            if ($cagnotte->getDonateur() === $this) {
                $cagnotte->setDonateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Conversation[]
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): self
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations[] = $conversation;
            $conversation->setAdherent($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): self
    {
        if ($this->conversations->removeElement($conversation)) {
            // set the owning side to null (unless already changed)
            if ($conversation->getAdherent() === $this) {
                $conversation->setAdherent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|EventAdherent[]
     */
    public function getEventAdherents(): Collection
    {
        return $this->eventAdherents;
    }

    public function addEventAdherent(EventAdherent $eventAdherent): self
    {
        if (!$this->eventAdherents->contains($eventAdherent)) {
            $this->eventAdherents[] = $eventAdherent;
            $eventAdherent->setAdherent($this);
        }

        return $this;
    }

    public function removeEventAdherent(EventAdherent $eventAdherent): self
    {
        if ($this->eventAdherents->removeElement($eventAdherent)) {
            // set the owning side to null (unless already changed)
            if ($eventAdherent->getAdherent() === $this) {
                $eventAdherent->setAdherent(null);
            }
        }

        return $this;
    }

}

app/src/Entity/Cagnotte.php
<?php

namespace App\Entity;

use App\Repository\CagnotteRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CagnotteRepository::class)
 */
class Cagnotte
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotNull(message="Le montant ne peut pas être vide")
     */
    private $montant;

    /**
     * @ORM\ManyToOne(targetEntity=Adherent::class, inversedBy="cagnottes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $donateur;

    /**
     * @ORM\ManyToOne(targetEntity=Association::class, inversedBy="cagnottes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $association;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMontant(): ?float
    {
        return $this->montant;
    }

    public function setMontant(float $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDonateur(): ?Adherent
    {
        return $this->donateur;
    }

    public function setDonateur(?Adherent $donateur): self
    {
        $this->donateur = $donateur;

        return $this;
    }

    public function getAssociation(): ?Association
    {
        return $this->association;
    }

    public function setAssociation(?Association $association): self
    {
        $this->association = $association;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

app/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;
use DateTime;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Publication::class, inversedBy="commentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $publication_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }


    public function setCreatedAt(): self
    {
        $this->created_at = new DateTime();
        return $this;
    }

    public function getPublicationId(): ?Publication
    {
        return $this->publication_id;
    }

    public function setPublicationId(?Publication $publication_id): self
    {
        $this->publication_id = $publication_id;

        return $this;
    }
}

app/src/Form/CagnotteType.php
<?php

namespace App\Form;

use App\Entity\Cagnotte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CagnotteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('montant',IntegerType::class,[
                'label' => false,
                'attr' => [
                    'class' => 'form-control',
                    'placeholder' => 'Montant du don'
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Valider',
                'attr' => [
                    'class' => 'w-100 mt-2 btn btn-primary',
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Cagnotte::class,
        ]);
    }
}

app/src/Controller/Cagnotte/CagnotteController.php
<?php

namespace App\Controller\Cagnotte;

use App\Entity\Association;
use App\Entity\Cagnotte;
use App\Form\CagnotteType;
use App\Service\EmailService;
use Doctrine\ORM\EntityManagerInterface;
use PhpParser\Error;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Stripe\PaymentIntent;
use Stripe\Stripe;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;

class CagnotteController extends AbstractController
{
    private $em;
    //private $requestStack;
    private $emailService;

    public function __construct(EntityManagerInterface $em, /*RequestStack $requestStack */EmailService $emailService)
    {
        $this->em = $em;
        //$this->requestStack = $requestStack;
        $this->emailService = $emailService;
    }

    protected function getSessionForm($key){
        $session = new Session();
        if($session->get($key)){
            $session->remove($key);
            return true;
        }
        return false;
    }

    /**
     * @Route("/cagnotte/paiement/{id}", name="payment")
     * @Security("is_granted('ROLE_ADH_CONFIRME')", statusCode=403, message="Acces denied")
     */
    public function cagnotte(Association $association): Response
    {
        if(!$association->getHaveCagnotte()){
            return $this->redirectToRoute('profile_account');
        }
        $sessionForm = $this->getSessionForm('form');
        if($sessionForm) return $this->redirectToRoute("default_connect");
        $form = $this->createForm(CagnotteType::class);
        return $this->render('cagnotte/index.html.twig',[
            "form" => $form->createView(),
            "association" => $association
        ]);
    }

    /**
     * @Route("/cagnotte/merci", name="merci", methods={"POST"})
     * @Security("is_granted('ROLE_ADH_CONFIRME')", statusCode=403, message="Acces denied")
     */
    public function merci(Request $request): Response{
        //requestStack -> use in 5.3 because new session is deprecated but docker use symfo 5.1
        //$session = $this->requestStack->getSession();

        $session = new Session();
        $sessionForm = $this->getSessionForm('form');
        if($sessionForm) return $this->redirectToRoute("default_connect");

        $data = $request->request->all();
        $cagnotte = new Cagnotte();
        $form = $this->createForm(CagnotteType::class,$cagnotte);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $cagnotte->setAssociation($this->em->getRepository(Association::class)->findOneById((int)$data["id-assoc"]));
            $cagnotte->setDonateur($this->getUser()->getAdherent());
            $cagnotte->setMontant((float) $data["cagnotte"]["montant"]);
            $this->em->persist($cagnotte);
            $this->em->flush();
            $session->set('form', 'true');
            $email = $cagnotte->getAssociation()->getUserAccount()->getEmail();
            $nameAssoc = $cagnotte->getAssociation()->getName();
            $this->emailService->sendMail("Don : Confirmation de don pour $nameAssoc",$email,[$this->renderView(
                'emails/don-facture.html.twig', ['cagnotte' => $cagnotte]
            ),'text/html']);
        }

        return $this->render('cagnotte/merci.html.twig',[
            "cagnotte" => $cagnotte
        ]);
    }

    /**
     * @Route("ma-cagnotte",name="ma-cagnotte")
     * @Security("is_granted('ROLE_ASSOC_CONFIRME')", statusCode=403, message="Acces denied")
     */
    public function maCagnotte(): Response
    {
        $association = $this->getUser()->getAssociation();
        $limite = !is_null($association->getLimitCagnotte()) ? $association->getLimitCagnotte() : 100;
        $som = 0;
        foreach($association->getCagnottes() as $cagnotte){
            $som += $cagnotte->getMontant();
        }
        $pourcentage = ($som * 100) / $limite;

        return $this->render('cagnotte/cagnotte.html.twig',[
            "som" => $som,
            "pourcentage" => $pourcentage,
            "limite" => $limite
        ]);
    }

    /**
     * @Route("/stripe", name="stripe")
     */
    public function stripe(): Response
    {
        Stripe::setApiKey('sk_test_51J6zl2BYvgiERdxUhmlt3VIiGu8b6IpcUAYdirr5r3aDJ8n8kavaA5ehrVS836UwziWI6uwzE469YYlwFrz6whoX00fQ4xJzRU');

        header('Content-Type: application/json');
        try {
            $json_str = file_get_contents('php://input');
            $json_obj = json_decode($json_str);

            $paymentIntent = PaymentIntent::create([
                'amount' => $json_obj->items[0]->price * 100,
                'description' =>  $json_obj->items[0]->name,
                'currency' => 'eur',
            ]);

            $output = [
                'clientSecret' => $paymentIntent->client_secret,
            ];

            return new JsonResponse($output);
        } catch (Error $e) {
            return new JsonResponse(['error' => $e->getMessage()],500);
        }
    }

}

app/templates/cagnotte/cagnotte.html.twig
{% extends 'base_connected.html.twig' %}

{% block title %} Ma cagnotte - AssoBook{% endblock %}
{% block stylesheets %}
    {{ parent() }}
{% endblock %}

{% block body %}
    <h1 class="text-center mt-4 mb-3">Ma cagnotte</h1>
    <div class="container">
        <div class="progress mb-3">
            <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:{{ pourcentage }}%;">
                <span style="font-size:{{ pourcentage < 10 ? "10px" : "12px" }};">{{ som }} / {{ limite }}</span>
            </div>
        </div>
        {% if(app.user.association.cagnottes is not empty) %}
            {% for don in app.user.association.cagnottes %}
                <div class="shadow p-3 mb-3 bg-white rounded">
                    <p class="m-0"><i class="fas fa-check-circle text-success"></i> {{ don.donateur.firstname|capitalize ~ ' ' ~ don.donateur.lastname|upper }}
                        vous a fait un don de <strong>{{ don.montant }} €</strong> le {{ don.createdAt|date('d/m/Y') }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p class="text-center">Votre association n'a reçu aucun don pour le moment. Revenez plus tard.</p>
        {% endif %}
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}

app/templates/cagnotte/index.html.twig
{% extends 'base_connected.html.twig' %}

{% block title %} Don {{ association.name }} - AssoBook{% endblock %}
{% block scripts %}
    <script src="https://js.stripe.com/v3/"></script>
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags("stripecss") }}
{% endblock %}

{% block body %}
    <h1 class="text-center mt-4">Montant du don</h1>
    <div class="container">
        <div class="choose-montant">
            <div class="row mt-4 mx-auto w-50">
                <div class="col-lg-3 col-sm-6 col-12 text-center"><button class="btn btn-primary mb-2 w-100 price" data-montant="25">25 €</button></div>
                <div class="col-lg-3 col-sm-6 col-12 text-center"><button class="btn btn-primary mb-2 w-100 price" data-montant="50">50 €</button></div>
                <div class="col-lg-3 col-sm-6 col-12 text-center"><button class="btn btn-primary mb-2 w-100 price" data-montant="100">100 €</button></div>
                <div class="col-lg-3 col-sm-6 col-12 text-center"><button class="btn btn-primary mb-2 w-100 price" data-montant="other">Autre</button></div>
            </div>
            <div class="mt-2 mx-auto w-50">
                <div class="px-2">
                    {{ form_start(form, {'action': path('cagnotte_merci')}) }}
                        <input name="id-assoc" value="{{ association.id }}" hidden>
                        <input name="name-assoc" value="{{ association.name }}" hidden>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('stripejs') }}
{% endblock %}

app/templates/cagnotte/merci.html.twig
{% extends 'base_connected.html.twig' %}

{% block title %} Merci - AssoBook{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('stripecss') }}
{% endblock %}

{% block body %}
    <div class="container">
        <div class="shadow p-3 m-5 bg-white rounded">
            <div class="d-flex justify-content-center align-items-center">
                <i class="fas fa-check-circle mr-3"></i>
                <h1 class="text-center mt-4 mb-4">Merci pour votre don</h1>
            </div>
            <div class="info-client row justify-content-center">
                <p><strong>Information client : </strong></p>
                <div class="col-12 text-center"><strong>Nom :</strong> {{ cagnotte.donateur.lastname|upper }}</div>
                <div class="col-12 text-center"><strong>Prénom :</strong> : {{ cagnotte.donateur.firstname|capitalize }}</div>
                <div class="col-12 text-center"><strong>Email :</strong> : {{ cagnotte.donateur.userAccount.email }}</div>
            </div>
            <div class="info-association row justify-content-center mt-4">
                <p><strong>Pour l'association : </strong></p>
                <div class="col-12 text-center"><strong>Nom :</strong> {{ cagnotte.association.name|capitalize }}</div>
                <div class="col-12 text-center"><strong>Email :</strong> {{ cagnotte.association.userAccount.email }}</div>
            </div>
            <div class="form-paiement mt-3">
                <div class="shadow p-3 mx-5 bg-white rounded row">
                    <div class="col-lg-4"><img src="{{ asset('assets/images/icons/don.png') }}" width="50" height="50" alt="don"></div>
                    <div class="col-lg-4 text-center my-auto">Don</div>
                    <div class="col-lg-4 text-right font-weight-bold my-auto">{{ cagnotte.montant}} €</div>
                </div>
            </div>
            <div class="d-flex justify-content-center mt-4">
                <a class="btn btn-form btn-form-blue w-25" href="{{ path('default_connect') }}">Retour accueil</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
{% endblock %}